version: '3.1'
services:
  dns:
    image: alpine  
    container_name: examen_tienda
    volumes:
      - ./conf/named.conf:/etc/bind/named.conf   # Archivo de configuración de bind9
      - ./zonas:/etc/bind/db.tienda              # Archivo de zona para tendaelectronica.int
    ports:
      - "54:54"   
    networks:
      - red1
    restart: always

networks:
  red1:
    driver: bridge

